### ISSUE TITLE
Deleted posts still show up in feed

### ISSUE THREAD

**Issue by soniakandah** [moduleon/grav-plugin-social-feed#10]
Not sure if this is a feature or a bug - it seems like although new posts show up in the feed, if those posts are later deleted the feed doesn't remove it from the list. Any more info you can give on this?

**Comment by moduleon** [comment]
Hi, this feature is not implemented. Could be something interesting if you're up for a PR :)

**Comment by soniakandah** [comment]
Haha I'll think on it!
