### ISSUE TITLE
Some twitter images not loading

### ISSUE THREAD

**Issue by janvanreeth** [moduleon/grav-plugin-social-feed#11]
Hi,

There's a problem with some Tweets not returning images. I've checked in the json return as well.
Probably because the tweed_mode needs to be set to extended. If you add tweet_mode=extended to the json url as a test, every object contains the entities media_url, but if the extended mode is not active, some objects don't have it. 

Any idea how we can activate extended mode for tweets?

**Comment by moduleon** [comment]
Hi,

The plugin does not take these "extended mode" in charge. Would you take time to fork the repo, work on it, and make PR maybe ?

**Comment by moduleon** [comment]
Hi again, I have run some tests, and I had no problem for retrieving images.
Can you give an example of a public twitter username with post having no image ?

**Comment by janvanreeth** [comment]
Hello, 
I was using it for our new company website, the twitter userame is @bewirebe.
Also when changing the inclusion of retweets in TwitterApi.php on line 32 will not provide any images.

Here an example how the image from the post is not present (Second block):
<img width="1345" alt="screenshot 2019-01-14 at 10 53 27" src="https://user-images.githubusercontent.com/17739944/51106141-324a6300-17eb-11e9-8008-c2b89de56b75.png">

<img width="669" alt="screenshot 2019-01-14 at 10 57 49" src="https://user-images.githubusercontent.com/17739944/51106182-51e18b80-17eb-11e9-968a-5702e55f4fec.png">

**Comment by moduleon** [comment]
What does the network say? 
-> Do you have an empty value for the image attribute in the post?
-> Do you have an error on the image request?
