### ISSUE TITLE
Completely broken for Instagram

### ISSUE THREAD

**Issue by tchapi** [moduleon/grav-plugin-social-feed#12]
This plugin is completely broken for Instagram, partly I think because it relies on a deleted library : https://github.com/php-instagram-api/php-instagram-api and also because the configuration sets an `instagram_client_id` and that the code expects an `instagram_client_secret` ...

Or am I missing something ?
Thanks a lot !

**Comment by moduleon** [comment]
Hi,

Actually, the repository still exist. It is now the https://github.com/galen/PHP-Instagram-API.
But there were a bug for instagram_client_id not set. I made a bugfix for that.

See https://github.com/moduleon/grav-plugin-social-feed/pull/14

Be aware, Instagram broke the public users search entrypoint. The only one you can get is your user only (the one corresponding to the access token provided).

**Comment by tchapi** [comment]
Oh, nice.
I think you should update the `composer.json` file then, since it still points to the non-existing repository.

I'll test the module with your merged PR asap
Thanks a lot

**Comment by tchapi** [comment]
Hm it seems that GPM is not picking up your update

    GPM Releases Configuration: Testing

    Found 11 packages installed of which 3 need updating
    Packages not found or not requiring updates: social-feed

I think it's because the version in your blueprint has remained the same — you may want to bump it up to 0.1.3

Thanks

**Comment by tchapi** [comment]
Ping @moduleon if you ever have the time to make a release with the correct blueprint version

**Comment by moduleon** [comment]
Hi, sorry for the delay! I did update the blueprint. Thank you for noticing this
