### ISSUE TITLE
Fresh install- not working.

### ISSUE THREAD

**Issue by adavie1** [moduleon/grav-plugin-social-feed#16]
I've added the composer dependencies etc.
However I get this warning from  composer:

`Package facebook/php-sdk-v4 is abandoned, you should avoid using it. Use facebook/graph-sdk instead.`

Also, I've set up a page, as Twig (not markdown), with the following code:

```
{% set postData = socialPosts() %}
    <ul>
        {% for post in postData.posts %}
        <li>{{ post.body }}</li>
        {% endfor %}
    </ul>

```
Already got my FB API and key set up in the plugin.

I get a blank page, see: [example page](http://quantumwealth.net/fb-feed)

What am I missing?

**Comment by moduleon** [comment]
Hi,

First, if you installed this plugin with GPM, you should not have to add any dependencies in your composer.json. Nevertheless, this dependency is abandonned, and should be replaced. But, a lot of work has to be done to make it work correctly. Any help would be appreciated if you're up to.

Secondly, you have to launch the script to import your posts locally. Please see https://github.com/moduleon/grav-plugin-social-feed#cli-commands-

Hope this helps

**Comment by adavie1** [comment]
Hi, thanks for the quick response. I installed via the admin panel. Let me check the link. I'll get back to you shortly.

**Comment by adavie1** [comment]
Yes, it works using GPM, plus the rest of the setup as given. However, I still feel this should be handled via the admin interface when installing via that.
Thanks for the response. Useful plugin.
