### ISSUE TITLE
Unable to Fetch new Posts

### ISSUE THREAD

**Issue by Thoomyy** [moduleon/grav-plugin-social-feed#17]
Hi

If i try to fetch posts on terminal I get the Error "Access to undeclared static property"
Someone else get this error?

But I only have the problem with PHP 7.1 and 7.2 (7.3 not tested).
If I try with PHP 7.0 (with an older grav CMS) the fetch works.
But the latest version of grav CMS does not work with PHP 7.0

I think the problem arise because of using `self:: `

Can someone help?

Full Error:
```
PHP Fatal error:  Uncaught Error: Access to undeclared static property: Grav\Plugin\Console\SocialFeedCommand::$grav in .../user/plugins/social-feed/cli/SocialFeedCommand.php:21
Stack trace:
#0 .../bin/plugin(146): Grav\Plugin\Console\SocialFeedCommand->__construct()
#1 {main}
  thrown in .../user/plugins/social-feed/cli/SocialFeedCommand.php on line 21
```

**Comment by cahsmrj** [comment]
I also have this issue using php 7.3.  I would love a solution of how to change that line 21.
