### ISSUE TITLE
Does not work with current Grav version?

### ISSUE THREAD

**Issue by MrMacStripe** [moduleon/grav-plugin-social-feed#3]
Hi, 
I get the following error when the plugin is enabled. It does not matter if I enter anything in the plugin fields. Empty and filled with correct values, I get:

Error
Class 'Grav\Plugin\SocialFeed\Twig\PostExtension' not found

**Comment by moduleon** [comment]
Hi,

When I created this plugin, I thought that the command `bin/gpm install social-feed` would install the dependencies declared in the composer.json file. But, it does not, and I will be forced in a future to add dependencies as versionned files, and add a custom autoloader for registering the plugin namespace.

However, you can still make the plugin work. You just have to follow these steps:

1. Add these lines in the composer.json of your grav project:
```json
    "require": {
        ...
        "facebook/php-sdk-v4" : "4.0.*",
        "php-instagram-api/php-instagram-api": "dev-master",
        "themattharris/tmhoauth": "~0.8.4"
    },
    ...
    "autoload": {
        "psr-4": {
            ...
            "Grav\\Plugin\\SocialFeed\\": "user/plugins/social-feed/src/"
        },
        ...
    },
```

2. Install composer in your grav project. You can go to https://getcomposer.org/download/, or, use the zip I attached to this comment. In this last case, just unzip, and put composer.phar in your grav project.
[composer.zip](https://github.com/moduleon/grav-plugin-social-feed/files/1447571/composer.zip)

3. Then, run in your terminal: 
```shell
$ cd /path/to/my/grav/project
$ php composer.phar update
``` 

Hope that helps!

**Comment by moduleon** [comment]
I decided to fix the problem right now. You can download now the last release, remove the folder social-feed installed by grav (in user/plugins folder), put the new one instead and rename it as social-feed. It should work then.
