### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by damerms** [moduleon/grav-plugin-social-feed#5]
Hi, 

I am confused on the setup. I have an .md file for the social feed. Are we supposed to create an equivalent social feed twig file? 

Where does this sample code go?

{% set postData = socialPosts() %}
<ul>
    {% for post in postData.posts %}
    <li>{{ post.body }}</li>
    {% endfor %}
</ul>

**Comment by moduleon** [comment]
Hi,

Yes, `{% set postData = socialPosts() %}` refers to a twig function named `socialPosts()`, so you have to use twig template instead of markdown in order to display your posts.

**Comment by damerms** [comment]
Hi Kevin,

I can't seem to get it to work, but thanks for your help. I will try in the
future.
ᐧ

Thanks
David Mermelstein

Shaping Connected Experiences
 Linkedin <http://www.linkedin.com/in/merms> | 773.744.0760

“Before jumping right into solving a problem, we should step back and
invest time and effort to improve our understanding of it.”

- Albert Einstein
